# Site settings
title: Clean
email: 1106389093@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/clean" # the subpath of your site, e.g. /blog/
url: "https://wuxirne.github.io/wuxiren.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  wuxirne

# Build settings
markdown: kramdown

# paginate
#plugins: [jekyll-paginate]
port: 4001
